name: Pages

on:
  push:
    branches: [ "3.0-dev" ]
  pull_request:
    branches: [ "3.0-dev" ]
  workflow_call:
    inputs:
      ref_name:
        type: string
        required: false
        default: "${{ github.ref_name }}"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome

    steps:
      - uses: actions/checkout@v3
        with:
          ref: "${{ inputs.ref_name }}"

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          pip install .[dev]

      - name: Build the pages
        run: |
          lookatme --tutorial --output tutorial_files --format html


      - name: Upload pages artifacts
        uses: actions/upload-pages-artifact@v1.0.7
        with:
          name: github-pages
          path: tutorial_files

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
    - name: Deploy pages
      id: deployment
      uses: actions/deploy-pages@v1.2.3
