name: Publish to PyPI
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Fill placeholders
        run: |
          version_num="${{github.ref_name}}"
          # strip the leading v
          version_num=${version_num#v}
          bin/fill_placeholders "$version_num"
      - name: Install pypa/build
        run: python -m pip install build --user
      - name: Build binary wheel + tarball
        run: python -m build --sdist --wheel --outdir dist/
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
